# "ported" by Adam Miller <maxamillion@fedoraproject.org> from
#   https://github.com/fedora-cloud/Fedora-Dockerfiles
#
# Originally written for Fedora-Dockerfiles by
#   scollier <scollier@redhat.com>

FROM nginx
MAINTAINER The EDU Project <ballo72@naver.com>

ENV LC_ALL en_US.UTF-8


COPY ./index.html /usr/share/nginx/html/
#RUN chmod 755 /start.sh

# ENTRYPOINT ["/xx/sshd","sshd"]
#CMD /start.sh